-- A new generation gets new tables. No REPLACE, mutation, or historical
-- partition overwrite is part of the Wiki source-evidence read path.
CREATE TABLE IF NOT EXISTS {database}.ods_wiki_prefix_event (
  producer String,
  source_offset Int64,
  event_id String,
  event_type String,
  status String,
  event_spec_jcs String,
  event_jcs_sha256 String,
  dc_receipt String,
  dc_receipt_sha256 String,
  rtw_original_event String,
  rtw_original_event_sha256 String,
  fact_set_payload_jcs String,
  fact_set_payload_jcs_sha256 String,
  acknowledged_cutoff_offset Int64,
  ods_evidence_sha256 String,
  dc_index_sha256 String
) ENGINE = MergeTree ORDER BY (producer, acknowledged_cutoff_offset, source_offset);

CREATE TABLE IF NOT EXISTS {database}.ods_wiki_catalog_fact (
  producer String,
  catalog_offset Int64,
  catalog_event_id String,
  catalog_event_raw_sha256 String,
  catalog_event_jcs_sha256 String,
  catalog_dc_receipt_sha256 String,
  fact_set_payload_jcs_sha256 String,
  module_id String,
  page_id String,
  wiki_revision_id String,
  fact_set_revision_id String,
  source_scope_revision String,
  fact_id String,
  source_revision_id String,
  source_content_sha256 String,
  locator String,
  source_byte_start String,
  source_byte_end String,
  source_quote String,
  source_quote_sha256 String,
  required Bool,
  conflict_group String,
  facts_complete_declared Bool,
  declaration_source String,
  rtw_actor_id String,
  acknowledged_cutoff_offset Int64,
  quality_state String
) ENGINE = MergeTree ORDER BY (producer, fact_set_revision_id, acknowledged_cutoff_offset, fact_id);

CREATE TABLE IF NOT EXISTS {database}.ods_wiki_judgment_revision (
  producer String,
  source_offset Int64,
  event_id String,
  event_raw_sha256 String,
  event_jcs_sha256 String,
  dc_receipt_sha256 String,
  module_id String,
  page_id String,
  wiki_revision_id String,
  fact_set_revision_id String,
  source_scope_revision String,
  fact_id String,
  judgment_id String,
  judge_revision_id String,
  judge_revision String,
  base_judge_revision_id String,
  source_revision_id String,
  source_quote_sha256 String,
  assessment String,
  claimed_grade Nullable(Int16),
  claimed_citation_present Bool,
  rtw_actor_id String,
  acknowledged_cutoff_offset Int64,
  quality_state String
) ENGINE = MergeTree ORDER BY (producer, fact_set_revision_id, acknowledged_cutoff_offset, fact_id, source_offset);
