// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	async "github.com/Sea-Go/Sea-BreakTheWaves/service/async/api/internal/handler/async"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/async/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/events",
				Handler: async.EventsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/processing/state",
				Handler: async.ProcessingStateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/projections/state",
				Handler: async.ProjectionStateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/async"),
	)
}
