// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type EventBatchReq struct {
	Events []map[string]string `json:"events"`
}

type EventBatchResp struct {
	Accepted int32  `json:"accepted"`
	ErrMsg   string `json:"err_msg,optional"`
}

type ProcessingStateResp struct {
	State string `json:"state"`
}
