// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	recommendadmin "github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/api/internal/handler/recommendadmin"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/reco/evaluation/summary",
				Handler: recommendadmin.EvaluationSummaryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)
}
