// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/recommendation/v1/recommendation.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecommendRequest 推荐请求
type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecRequestId  string                 `protobuf:"bytes,1,opt,name=rec_request_id,json=recRequestId,proto3" json:"rec_request_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Surface       string                 `protobuf:"bytes,6,opt,name=surface,proto3" json:"surface,omitempty"`
	PeriodBucket  string                 `protobuf:"bytes,7,opt,name=period_bucket,json=periodBucket,proto3" json:"period_bucket,omitempty"`
	Topk          int32                  `protobuf:"varint,8,opt,name=topk,proto3" json:"topk,omitempty"`
	Explain       bool                   `protobuf:"varint,9,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetRecRequestId() string {
	if x != nil {
		return x.RecRequestId
	}
	return ""
}

func (x *RecommendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecommendRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecommendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecommendRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *RecommendRequest) GetPeriodBucket() string {
	if x != nil {
		return x.PeriodBucket
	}
	return ""
}

func (x *RecommendRequest) GetTopk() int32 {
	if x != nil {
		return x.Topk
	}
	return 0
}

func (x *RecommendRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

// RecommendResponse 推荐响应
type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RecRequestId  string                 `protobuf:"bytes,2,opt,name=rec_request_id,json=recRequestId,proto3" json:"rec_request_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RecommendResponse) GetRecRequestId() string {
	if x != nil {
		return x.RecRequestId
	}
	return ""
}

func (x *RecommendResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecommendResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// ContentSearchRequest 内容搜索请求
type ContentSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchRequestId string                 `protobuf:"bytes,1,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Query           string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Topk            int32                  `protobuf:"varint,4,opt,name=topk,proto3" json:"topk,omitempty"`
	TopK            int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	RecallK         int32                  `protobuf:"varint,6,opt,name=recall_k,json=recallK,proto3" json:"recall_k,omitempty"`
	CoarseRecallK   int32                  `protobuf:"varint,7,opt,name=coarse_recall_k,json=coarseRecallK,proto3" json:"coarse_recall_k,omitempty"`
	MinPassScore    float32                `protobuf:"fixed32,8,opt,name=min_pass_score,json=minPassScore,proto3" json:"min_pass_score,omitempty"`
	Explain         bool                   `protobuf:"varint,9,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContentSearchRequest) Reset() {
	*x = ContentSearchRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSearchRequest) ProtoMessage() {}

func (x *ContentSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSearchRequest.ProtoReflect.Descriptor instead.
func (*ContentSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *ContentSearchRequest) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *ContentSearchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ContentSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ContentSearchRequest) GetTopk() int32 {
	if x != nil {
		return x.Topk
	}
	return 0
}

func (x *ContentSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ContentSearchRequest) GetRecallK() int32 {
	if x != nil {
		return x.RecallK
	}
	return 0
}

func (x *ContentSearchRequest) GetCoarseRecallK() int32 {
	if x != nil {
		return x.CoarseRecallK
	}
	return 0
}

func (x *ContentSearchRequest) GetMinPassScore() float32 {
	if x != nil {
		return x.MinPassScore
	}
	return 0
}

func (x *ContentSearchRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

// ContentSearchResponse 内容搜索响应
type ContentSearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SearchRequestId string                 `protobuf:"bytes,2,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContentSearchResponse) Reset() {
	*x = ContentSearchResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSearchResponse) ProtoMessage() {}

func (x *ContentSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSearchResponse.ProtoReflect.Descriptor instead.
func (*ContentSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{3}
}

func (x *ContentSearchResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ContentSearchResponse) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *ContentSearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// IngestRequest 文档入库请求
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ArticleJson   string                 `protobuf:"bytes,3,opt,name=article_json,json=articleJson,proto3" json:"article_json,omitempty"`
	Markdown      string                 `protobuf:"bytes,4,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{4}
}

func (x *IngestRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *IngestRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *IngestRequest) GetArticleJson() string {
	if x != nil {
		return x.ArticleJson
	}
	return ""
}

func (x *IngestRequest) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *IngestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IngestRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

// IngestResponse 文档入库响应
type IngestResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ArticleId            string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	CoarseVectorInserted bool                   `protobuf:"varint,2,opt,name=coarse_vector_inserted,json=coarseVectorInserted,proto3" json:"coarse_vector_inserted,omitempty"`
	FineVectorInserted   int32                  `protobuf:"varint,3,opt,name=fine_vector_inserted,json=fineVectorInserted,proto3" json:"fine_vector_inserted,omitempty"`
	FineChunkCount       int32                  `protobuf:"varint,4,opt,name=fine_chunk_count,json=fineChunkCount,proto3" json:"fine_chunk_count,omitempty"`
	ImageVectorInserted  int32                  `protobuf:"varint,5,opt,name=image_vector_inserted,json=imageVectorInserted,proto3" json:"image_vector_inserted,omitempty"`
	ImageChunkCount      int32                  `protobuf:"varint,6,opt,name=image_chunk_count,json=imageChunkCount,proto3" json:"image_chunk_count,omitempty"`
	GraphEnabled         bool                   `protobuf:"varint,7,opt,name=graph_enabled,json=graphEnabled,proto3" json:"graph_enabled,omitempty"`
	GraphWriteOk         bool                   `protobuf:"varint,8,opt,name=graph_write_ok,json=graphWriteOk,proto3" json:"graph_write_ok,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{5}
}

func (x *IngestResponse) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *IngestResponse) GetCoarseVectorInserted() bool {
	if x != nil {
		return x.CoarseVectorInserted
	}
	return false
}

func (x *IngestResponse) GetFineVectorInserted() int32 {
	if x != nil {
		return x.FineVectorInserted
	}
	return 0
}

func (x *IngestResponse) GetFineChunkCount() int32 {
	if x != nil {
		return x.FineChunkCount
	}
	return 0
}

func (x *IngestResponse) GetImageVectorInserted() int32 {
	if x != nil {
		return x.ImageVectorInserted
	}
	return 0
}

func (x *IngestResponse) GetImageChunkCount() int32 {
	if x != nil {
		return x.ImageChunkCount
	}
	return 0
}

func (x *IngestResponse) GetGraphEnabled() bool {
	if x != nil {
		return x.GraphEnabled
	}
	return false
}

func (x *IngestResponse) GetGraphWriteOk() bool {
	if x != nil {
		return x.GraphWriteOk
	}
	return false
}

// TitleSearchRequest 标题搜索请求
type TitleSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchRequestId string                 `protobuf:"bytes,1,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Query           string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Topk            int32                  `protobuf:"varint,3,opt,name=topk,proto3" json:"topk,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TitleSearchRequest) Reset() {
	*x = TitleSearchRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleSearchRequest) ProtoMessage() {}

func (x *TitleSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleSearchRequest.ProtoReflect.Descriptor instead.
func (*TitleSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{6}
}

func (x *TitleSearchRequest) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *TitleSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TitleSearchRequest) GetTopk() int32 {
	if x != nil {
		return x.Topk
	}
	return 0
}

// TitleSearchResponse 标题搜索响应
type TitleSearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SearchRequestId string                 `protobuf:"bytes,2,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TitleSearchResponse) Reset() {
	*x = TitleSearchResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleSearchResponse) ProtoMessage() {}

func (x *TitleSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleSearchResponse.ProtoReflect.Descriptor instead.
func (*TitleSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{7}
}

func (x *TitleSearchResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TitleSearchResponse) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *TitleSearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// AuthorSearchRequest 作者搜索请求
type AuthorSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchRequestId string                 `protobuf:"bytes,1,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Query           string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Topk            int32                  `protobuf:"varint,3,opt,name=topk,proto3" json:"topk,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorSearchRequest) Reset() {
	*x = AuthorSearchRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorSearchRequest) ProtoMessage() {}

func (x *AuthorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorSearchRequest.ProtoReflect.Descriptor instead.
func (*AuthorSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorSearchRequest) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *AuthorSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AuthorSearchRequest) GetTopk() int32 {
	if x != nil {
		return x.Topk
	}
	return 0
}

// AuthorSearchResponse 作者搜索响应
type AuthorSearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SearchRequestId string                 `protobuf:"bytes,2,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthorSearchResponse) Reset() {
	*x = AuthorSearchResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorSearchResponse) ProtoMessage() {}

func (x *AuthorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorSearchResponse.ProtoReflect.Descriptor instead.
func (*AuthorSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorSearchResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuthorSearchResponse) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *AuthorSearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// OnboardingRequest 新用户引导请求
type OnboardingRequest struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	RequestId                       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId                          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username                        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Interests                       []string               `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"`
	PrimaryPurpose                  string                 `protobuf:"bytes,5,opt,name=primary_purpose,json=primaryPurpose,proto3" json:"primary_purpose,omitempty"`
	PreferredArticleTypes           []string               `protobuf:"bytes,6,rep,name=preferred_article_types,json=preferredArticleTypes,proto3" json:"preferred_article_types,omitempty"`
	PreferredArticleLength          string                 `protobuf:"bytes,7,opt,name=preferred_article_length,json=preferredArticleLength,proto3" json:"preferred_article_length,omitempty"`
	PreferredStyle                  string                 `protobuf:"bytes,8,opt,name=preferred_style,json=preferredStyle,proto3" json:"preferred_style,omitempty"`
	Backgrounds                     []string               `protobuf:"bytes,9,rep,name=backgrounds,proto3" json:"backgrounds,omitempty"`
	DifficultyPreference            string                 `protobuf:"bytes,10,opt,name=difficulty_preference,json=difficultyPreference,proto3" json:"difficulty_preference,omitempty"`
	ExcludedContents                []string               `protobuf:"bytes,11,rep,name=excluded_contents,json=excludedContents,proto3" json:"excluded_contents,omitempty"`
	ReadingTimeSlots                []string               `protobuf:"bytes,12,rep,name=reading_time_slots,json=readingTimeSlots,proto3" json:"reading_time_slots,omitempty"`
	PersonalizedRecommendationTypes []string               `protobuf:"bytes,13,rep,name=personalized_recommendation_types,json=personalizedRecommendationTypes,proto3" json:"personalized_recommendation_types,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *OnboardingRequest) Reset() {
	*x = OnboardingRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingRequest) ProtoMessage() {}

func (x *OnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingRequest.ProtoReflect.Descriptor instead.
func (*OnboardingRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{10}
}

func (x *OnboardingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OnboardingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OnboardingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OnboardingRequest) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *OnboardingRequest) GetPrimaryPurpose() string {
	if x != nil {
		return x.PrimaryPurpose
	}
	return ""
}

func (x *OnboardingRequest) GetPreferredArticleTypes() []string {
	if x != nil {
		return x.PreferredArticleTypes
	}
	return nil
}

func (x *OnboardingRequest) GetPreferredArticleLength() string {
	if x != nil {
		return x.PreferredArticleLength
	}
	return ""
}

func (x *OnboardingRequest) GetPreferredStyle() string {
	if x != nil {
		return x.PreferredStyle
	}
	return ""
}

func (x *OnboardingRequest) GetBackgrounds() []string {
	if x != nil {
		return x.Backgrounds
	}
	return nil
}

func (x *OnboardingRequest) GetDifficultyPreference() string {
	if x != nil {
		return x.DifficultyPreference
	}
	return ""
}

func (x *OnboardingRequest) GetExcludedContents() []string {
	if x != nil {
		return x.ExcludedContents
	}
	return nil
}

func (x *OnboardingRequest) GetReadingTimeSlots() []string {
	if x != nil {
		return x.ReadingTimeSlots
	}
	return nil
}

func (x *OnboardingRequest) GetPersonalizedRecommendationTypes() []string {
	if x != nil {
		return x.PersonalizedRecommendationTypes
	}
	return nil
}

// OnboardingResponse 新用户引导响应
type OnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PeriodBucket  string                 `protobuf:"bytes,5,opt,name=period_bucket,json=periodBucket,proto3" json:"period_bucket,omitempty"`
	MemoryTypes   []string               `protobuf:"bytes,6,rep,name=memory_types,json=memoryTypes,proto3" json:"memory_types,omitempty"`
	Warnings      []string               `protobuf:"bytes,7,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardingResponse) Reset() {
	*x = OnboardingResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardingResponse) ProtoMessage() {}

func (x *OnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardingResponse.ProtoReflect.Descriptor instead.
func (*OnboardingResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{11}
}

func (x *OnboardingResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *OnboardingResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *OnboardingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnboardingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OnboardingResponse) GetPeriodBucket() string {
	if x != nil {
		return x.PeriodBucket
	}
	return ""
}

func (x *OnboardingResponse) GetMemoryTypes() []string {
	if x != nil {
		return x.MemoryTypes
	}
	return nil
}

func (x *OnboardingResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// HealthResponse 健康检查响应
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ToolListResponse 工具列表响应
type ToolListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolListResponse) Reset() {
	*x = ToolListResponse{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolListResponse) ProtoMessage() {}

func (x *ToolListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolListResponse.ProtoReflect.Descriptor instead.
func (*ToolListResponse) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{13}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{14}
}

type ToolListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolListRequest) Reset() {
	*x = ToolListRequest{}
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolListRequest) ProtoMessage() {}

func (x *ToolListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_recommendation_v1_recommendation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolListRequest.ProtoReflect.Descriptor instead.
func (*ToolListRequest) Descriptor() ([]byte, []int) {
	return file_api_recommendation_v1_recommendation_proto_rawDescGZIP(), []int{15}
}

var File_api_recommendation_v1_recommendation_proto protoreflect.FileDescriptor

const file_api_recommendation_v1_recommendation_proto_rawDesc = "" +
	"\n" +
	"*api/recommendation/v1/recommendation.proto\x12\x11recommendation.v1\"\x92\x02\n" +
	"\x10RecommendRequest\x12$\n" +
	"\x0erec_request_id\x18\x01 \x01(\tR\frecRequestId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x18\n" +
	"\asurface\x18\x06 \x01(\tR\asurface\x12#\n" +
	"\rperiod_bucket\x18\a \x01(\tR\fperiodBucket\x12\x12\n" +
	"\x04topk\x18\b \x01(\x05R\x04topk\x12\x18\n" +
	"\aexplain\x18\t \x01(\bR\aexplain\"\x8e\x01\n" +
	"\x11RecommendResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12$\n" +
	"\x0erec_request_id\x18\x02 \x01(\tR\frecRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"\xa3\x02\n" +
	"\x14ContentSearchRequest\x12*\n" +
	"\x11search_request_id\x18\x01 \x01(\tR\x0fsearchRequestId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x12\n" +
	"\x04topk\x18\x04 \x01(\x05R\x04topk\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12\x19\n" +
	"\brecall_k\x18\x06 \x01(\x05R\arecallK\x12&\n" +
	"\x0fcoarse_recall_k\x18\a \x01(\x05R\rcoarseRecallK\x12$\n" +
	"\x0emin_pass_score\x18\b \x01(\x02R\fminPassScore\x12\x18\n" +
	"\aexplain\x18\t \x01(\bR\aexplain\"v\n" +
	"\x15ContentSearchResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12*\n" +
	"\x11search_request_id\x18\x02 \x01(\tR\x0fsearchRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xaf\x01\n" +
	"\rIngestRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12!\n" +
	"\farticle_json\x18\x03 \x01(\tR\varticleJson\x12\x1a\n" +
	"\bmarkdown\x18\x04 \x01(\tR\bmarkdown\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\"\xec\x02\n" +
	"\x0eIngestResponse\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x124\n" +
	"\x16coarse_vector_inserted\x18\x02 \x01(\bR\x14coarseVectorInserted\x120\n" +
	"\x14fine_vector_inserted\x18\x03 \x01(\x05R\x12fineVectorInserted\x12(\n" +
	"\x10fine_chunk_count\x18\x04 \x01(\x05R\x0efineChunkCount\x122\n" +
	"\x15image_vector_inserted\x18\x05 \x01(\x05R\x13imageVectorInserted\x12*\n" +
	"\x11image_chunk_count\x18\x06 \x01(\x05R\x0fimageChunkCount\x12#\n" +
	"\rgraph_enabled\x18\a \x01(\bR\fgraphEnabled\x12$\n" +
	"\x0egraph_write_ok\x18\b \x01(\bR\fgraphWriteOk\"j\n" +
	"\x12TitleSearchRequest\x12*\n" +
	"\x11search_request_id\x18\x01 \x01(\tR\x0fsearchRequestId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04topk\x18\x03 \x01(\x05R\x04topk\"t\n" +
	"\x13TitleSearchResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12*\n" +
	"\x11search_request_id\x18\x02 \x01(\tR\x0fsearchRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"k\n" +
	"\x13AuthorSearchRequest\x12*\n" +
	"\x11search_request_id\x18\x01 \x01(\tR\x0fsearchRequestId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x12\n" +
	"\x04topk\x18\x03 \x01(\x05R\x04topk\"u\n" +
	"\x14AuthorSearchResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12*\n" +
	"\x11search_request_id\x18\x02 \x01(\tR\x0fsearchRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xc7\x04\n" +
	"\x11OnboardingRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1c\n" +
	"\tinterests\x18\x04 \x03(\tR\tinterests\x12'\n" +
	"\x0fprimary_purpose\x18\x05 \x01(\tR\x0eprimaryPurpose\x126\n" +
	"\x17preferred_article_types\x18\x06 \x03(\tR\x15preferredArticleTypes\x128\n" +
	"\x18preferred_article_length\x18\a \x01(\tR\x16preferredArticleLength\x12'\n" +
	"\x0fpreferred_style\x18\b \x01(\tR\x0epreferredStyle\x12 \n" +
	"\vbackgrounds\x18\t \x03(\tR\vbackgrounds\x123\n" +
	"\x15difficulty_preference\x18\n" +
	" \x01(\tR\x14difficultyPreference\x12+\n" +
	"\x11excluded_contents\x18\v \x03(\tR\x10excludedContents\x12,\n" +
	"\x12reading_time_slots\x18\f \x03(\tR\x10readingTimeSlots\x12J\n" +
	"!personalized_recommendation_types\x18\r \x03(\tR\x1fpersonalizedRecommendationTypes\"\xe3\x01\n" +
	"\x12OnboardingResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12#\n" +
	"\rperiod_bucket\x18\x05 \x01(\tR\fperiodBucket\x12!\n" +
	"\fmemory_types\x18\x06 \x03(\tR\vmemoryTypes\x12\x1a\n" +
	"\bwarnings\x18\a \x03(\tR\bwarnings\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x12\n" +
	"\x10ToolListResponse\"\x0f\n" +
	"\rHealthRequest\"\x11\n" +
	"\x0fToolListRequest2\xf4\x05\n" +
	"\x15RecommendationService\x12V\n" +
	"\tRecommend\x12#.recommendation.v1.RecommendRequest\x1a$.recommendation.v1.RecommendResponse\x12b\n" +
	"\rContentSearch\x12'.recommendation.v1.ContentSearchRequest\x1a(.recommendation.v1.ContentSearchResponse\x12U\n" +
	"\x0eIngestDocument\x12 .recommendation.v1.IngestRequest\x1a!.recommendation.v1.IngestResponse\x12\\\n" +
	"\vSearchTitle\x12%.recommendation.v1.TitleSearchRequest\x1a&.recommendation.v1.TitleSearchResponse\x12_\n" +
	"\fSearchAuthor\x12&.recommendation.v1.AuthorSearchRequest\x1a'.recommendation.v1.AuthorSearchResponse\x12_\n" +
	"\x10SubmitOnboarding\x12$.recommendation.v1.OnboardingRequest\x1a%.recommendation.v1.OnboardingResponse\x12R\n" +
	"\vHealthCheck\x12 .recommendation.v1.HealthRequest\x1a!.recommendation.v1.HealthResponse\x12T\n" +
	"\tListTools\x12\".recommendation.v1.ToolListRequest\x1a#.recommendation.v1.ToolListResponseB\x1bZ\x19sea/api/recommendation/v1b\x06proto3"

var (
	file_api_recommendation_v1_recommendation_proto_rawDescOnce sync.Once
	file_api_recommendation_v1_recommendation_proto_rawDescData []byte
)

func file_api_recommendation_v1_recommendation_proto_rawDescGZIP() []byte {
	file_api_recommendation_v1_recommendation_proto_rawDescOnce.Do(func() {
		file_api_recommendation_v1_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_recommendation_v1_recommendation_proto_rawDesc), len(file_api_recommendation_v1_recommendation_proto_rawDesc)))
	})
	return file_api_recommendation_v1_recommendation_proto_rawDescData
}

var file_api_recommendation_v1_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_recommendation_v1_recommendation_proto_goTypes = []any{
	(*RecommendRequest)(nil),      // 0: recommendation.v1.RecommendRequest
	(*RecommendResponse)(nil),     // 1: recommendation.v1.RecommendResponse
	(*ContentSearchRequest)(nil),  // 2: recommendation.v1.ContentSearchRequest
	(*ContentSearchResponse)(nil), // 3: recommendation.v1.ContentSearchResponse
	(*IngestRequest)(nil),         // 4: recommendation.v1.IngestRequest
	(*IngestResponse)(nil),        // 5: recommendation.v1.IngestResponse
	(*TitleSearchRequest)(nil),    // 6: recommendation.v1.TitleSearchRequest
	(*TitleSearchResponse)(nil),   // 7: recommendation.v1.TitleSearchResponse
	(*AuthorSearchRequest)(nil),   // 8: recommendation.v1.AuthorSearchRequest
	(*AuthorSearchResponse)(nil),  // 9: recommendation.v1.AuthorSearchResponse
	(*OnboardingRequest)(nil),     // 10: recommendation.v1.OnboardingRequest
	(*OnboardingResponse)(nil),    // 11: recommendation.v1.OnboardingResponse
	(*HealthResponse)(nil),        // 12: recommendation.v1.HealthResponse
	(*ToolListResponse)(nil),      // 13: recommendation.v1.ToolListResponse
	(*HealthRequest)(nil),         // 14: recommendation.v1.HealthRequest
	(*ToolListRequest)(nil),       // 15: recommendation.v1.ToolListRequest
}
var file_api_recommendation_v1_recommendation_proto_depIdxs = []int32{
	0,  // 0: recommendation.v1.RecommendationService.Recommend:input_type -> recommendation.v1.RecommendRequest
	2,  // 1: recommendation.v1.RecommendationService.ContentSearch:input_type -> recommendation.v1.ContentSearchRequest
	4,  // 2: recommendation.v1.RecommendationService.IngestDocument:input_type -> recommendation.v1.IngestRequest
	6,  // 3: recommendation.v1.RecommendationService.SearchTitle:input_type -> recommendation.v1.TitleSearchRequest
	8,  // 4: recommendation.v1.RecommendationService.SearchAuthor:input_type -> recommendation.v1.AuthorSearchRequest
	10, // 5: recommendation.v1.RecommendationService.SubmitOnboarding:input_type -> recommendation.v1.OnboardingRequest
	14, // 6: recommendation.v1.RecommendationService.HealthCheck:input_type -> recommendation.v1.HealthRequest
	15, // 7: recommendation.v1.RecommendationService.ListTools:input_type -> recommendation.v1.ToolListRequest
	1,  // 8: recommendation.v1.RecommendationService.Recommend:output_type -> recommendation.v1.RecommendResponse
	3,  // 9: recommendation.v1.RecommendationService.ContentSearch:output_type -> recommendation.v1.ContentSearchResponse
	5,  // 10: recommendation.v1.RecommendationService.IngestDocument:output_type -> recommendation.v1.IngestResponse
	7,  // 11: recommendation.v1.RecommendationService.SearchTitle:output_type -> recommendation.v1.TitleSearchResponse
	9,  // 12: recommendation.v1.RecommendationService.SearchAuthor:output_type -> recommendation.v1.AuthorSearchResponse
	11, // 13: recommendation.v1.RecommendationService.SubmitOnboarding:output_type -> recommendation.v1.OnboardingResponse
	12, // 14: recommendation.v1.RecommendationService.HealthCheck:output_type -> recommendation.v1.HealthResponse
	13, // 15: recommendation.v1.RecommendationService.ListTools:output_type -> recommendation.v1.ToolListResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_recommendation_v1_recommendation_proto_init() }
func file_api_recommendation_v1_recommendation_proto_init() {
	if File_api_recommendation_v1_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_recommendation_v1_recommendation_proto_rawDesc), len(file_api_recommendation_v1_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_recommendation_v1_recommendation_proto_goTypes,
		DependencyIndexes: file_api_recommendation_v1_recommendation_proto_depIdxs,
		MessageInfos:      file_api_recommendation_v1_recommendation_proto_msgTypes,
	}.Build()
	File_api_recommendation_v1_recommendation_proto = out.File
	file_api_recommendation_v1_recommendation_proto_goTypes = nil
	file_api_recommendation_v1_recommendation_proto_depIdxs = nil
}
