// Code generated by MockGen. DO NOT EDIT.
// Source: recommendation.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=recommendation_mock.go -package=v1 --source=recommendation.trpc.go -self_package=sea/api/recommendation/v1
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockRecommendationServiceService is a mock of RecommendationServiceService interface.
type MockRecommendationServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationServiceServiceMockRecorder
}

// MockRecommendationServiceServiceMockRecorder is the mock recorder for MockRecommendationServiceService.
type MockRecommendationServiceServiceMockRecorder struct {
	mock *MockRecommendationServiceService
}

// NewMockRecommendationServiceService creates a new mock instance.
func NewMockRecommendationServiceService(ctrl *gomock.Controller) *MockRecommendationServiceService {
	mock := &MockRecommendationServiceService{ctrl: ctrl}
	mock.recorder = &MockRecommendationServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationServiceService) EXPECT() *MockRecommendationServiceServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockRecommendationServiceService) ISGOMOCK() struct{} {
	return struct{}{}
}

// ContentSearch mocks base method.
func (m *MockRecommendationServiceService) ContentSearch(ctx context.Context, req *ContentSearchRequest) (*ContentSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentSearch", ctx, req)
	ret0, _ := ret[0].(*ContentSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContentSearch indicates an expected call of ContentSearch.
func (mr *MockRecommendationServiceServiceMockRecorder) ContentSearch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentSearch", reflect.TypeOf((*MockRecommendationServiceService)(nil).ContentSearch), ctx, req)
}

// HealthCheck mocks base method.
func (m *MockRecommendationServiceService) HealthCheck(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx, req)
	ret0, _ := ret[0].(*HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockRecommendationServiceServiceMockRecorder) HealthCheck(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockRecommendationServiceService)(nil).HealthCheck), ctx, req)
}

// IngestDocument mocks base method.
func (m *MockRecommendationServiceService) IngestDocument(ctx context.Context, req *IngestRequest) (*IngestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestDocument", ctx, req)
	ret0, _ := ret[0].(*IngestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestDocument indicates an expected call of IngestDocument.
func (mr *MockRecommendationServiceServiceMockRecorder) IngestDocument(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestDocument", reflect.TypeOf((*MockRecommendationServiceService)(nil).IngestDocument), ctx, req)
}

// ListTools mocks base method.
func (m *MockRecommendationServiceService) ListTools(ctx context.Context, req *ToolListRequest) (*ToolListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTools", ctx, req)
	ret0, _ := ret[0].(*ToolListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTools indicates an expected call of ListTools.
func (mr *MockRecommendationServiceServiceMockRecorder) ListTools(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockRecommendationServiceService)(nil).ListTools), ctx, req)
}

// Recommend mocks base method.
func (m *MockRecommendationServiceService) Recommend(ctx context.Context, req *RecommendRequest) (*RecommendResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommend", ctx, req)
	ret0, _ := ret[0].(*RecommendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockRecommendationServiceServiceMockRecorder) Recommend(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockRecommendationServiceService)(nil).Recommend), ctx, req)
}

// SearchAuthor mocks base method.
func (m *MockRecommendationServiceService) SearchAuthor(ctx context.Context, req *AuthorSearchRequest) (*AuthorSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAuthor", ctx, req)
	ret0, _ := ret[0].(*AuthorSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAuthor indicates an expected call of SearchAuthor.
func (mr *MockRecommendationServiceServiceMockRecorder) SearchAuthor(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAuthor", reflect.TypeOf((*MockRecommendationServiceService)(nil).SearchAuthor), ctx, req)
}

// SearchTitle mocks base method.
func (m *MockRecommendationServiceService) SearchTitle(ctx context.Context, req *TitleSearchRequest) (*TitleSearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTitle", ctx, req)
	ret0, _ := ret[0].(*TitleSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTitle indicates an expected call of SearchTitle.
func (mr *MockRecommendationServiceServiceMockRecorder) SearchTitle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTitle", reflect.TypeOf((*MockRecommendationServiceService)(nil).SearchTitle), ctx, req)
}

// SubmitOnboarding mocks base method.
func (m *MockRecommendationServiceService) SubmitOnboarding(ctx context.Context, req *OnboardingRequest) (*OnboardingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitOnboarding", ctx, req)
	ret0, _ := ret[0].(*OnboardingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitOnboarding indicates an expected call of SubmitOnboarding.
func (mr *MockRecommendationServiceServiceMockRecorder) SubmitOnboarding(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitOnboarding", reflect.TypeOf((*MockRecommendationServiceService)(nil).SubmitOnboarding), ctx, req)
}

// MockRecommendationServiceClientProxy is a mock of RecommendationServiceClientProxy interface.
type MockRecommendationServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationServiceClientProxyMockRecorder
}

// MockRecommendationServiceClientProxyMockRecorder is the mock recorder for MockRecommendationServiceClientProxy.
type MockRecommendationServiceClientProxyMockRecorder struct {
	mock *MockRecommendationServiceClientProxy
}

// NewMockRecommendationServiceClientProxy creates a new mock instance.
func NewMockRecommendationServiceClientProxy(ctrl *gomock.Controller) *MockRecommendationServiceClientProxy {
	mock := &MockRecommendationServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockRecommendationServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationServiceClientProxy) EXPECT() *MockRecommendationServiceClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockRecommendationServiceClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// ContentSearch mocks base method.
func (m *MockRecommendationServiceClientProxy) ContentSearch(ctx context.Context, req *ContentSearchRequest, opts ...client.Option) (*ContentSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ContentSearch", varargs...)
	ret0, _ := ret[0].(*ContentSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContentSearch indicates an expected call of ContentSearch.
func (mr *MockRecommendationServiceClientProxyMockRecorder) ContentSearch(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentSearch", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).ContentSearch), varargs...)
}

// HealthCheck mocks base method.
func (m *MockRecommendationServiceClientProxy) HealthCheck(ctx context.Context, req *HealthRequest, opts ...client.Option) (*HealthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HealthCheck", varargs...)
	ret0, _ := ret[0].(*HealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockRecommendationServiceClientProxyMockRecorder) HealthCheck(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).HealthCheck), varargs...)
}

// IngestDocument mocks base method.
func (m *MockRecommendationServiceClientProxy) IngestDocument(ctx context.Context, req *IngestRequest, opts ...client.Option) (*IngestResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IngestDocument", varargs...)
	ret0, _ := ret[0].(*IngestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestDocument indicates an expected call of IngestDocument.
func (mr *MockRecommendationServiceClientProxyMockRecorder) IngestDocument(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestDocument", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).IngestDocument), varargs...)
}

// ListTools mocks base method.
func (m *MockRecommendationServiceClientProxy) ListTools(ctx context.Context, req *ToolListRequest, opts ...client.Option) (*ToolListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTools", varargs...)
	ret0, _ := ret[0].(*ToolListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTools indicates an expected call of ListTools.
func (mr *MockRecommendationServiceClientProxyMockRecorder) ListTools(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).ListTools), varargs...)
}

// Recommend mocks base method.
func (m *MockRecommendationServiceClientProxy) Recommend(ctx context.Context, req *RecommendRequest, opts ...client.Option) (*RecommendResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Recommend", varargs...)
	ret0, _ := ret[0].(*RecommendResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockRecommendationServiceClientProxyMockRecorder) Recommend(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).Recommend), varargs...)
}

// SearchAuthor mocks base method.
func (m *MockRecommendationServiceClientProxy) SearchAuthor(ctx context.Context, req *AuthorSearchRequest, opts ...client.Option) (*AuthorSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchAuthor", varargs...)
	ret0, _ := ret[0].(*AuthorSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAuthor indicates an expected call of SearchAuthor.
func (mr *MockRecommendationServiceClientProxyMockRecorder) SearchAuthor(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAuthor", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).SearchAuthor), varargs...)
}

// SearchTitle mocks base method.
func (m *MockRecommendationServiceClientProxy) SearchTitle(ctx context.Context, req *TitleSearchRequest, opts ...client.Option) (*TitleSearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchTitle", varargs...)
	ret0, _ := ret[0].(*TitleSearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTitle indicates an expected call of SearchTitle.
func (mr *MockRecommendationServiceClientProxyMockRecorder) SearchTitle(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTitle", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).SearchTitle), varargs...)
}

// SubmitOnboarding mocks base method.
func (m *MockRecommendationServiceClientProxy) SubmitOnboarding(ctx context.Context, req *OnboardingRequest, opts ...client.Option) (*OnboardingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitOnboarding", varargs...)
	ret0, _ := ret[0].(*OnboardingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitOnboarding indicates an expected call of SubmitOnboarding.
func (mr *MockRecommendationServiceClientProxyMockRecorder) SubmitOnboarding(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitOnboarding", reflect.TypeOf((*MockRecommendationServiceClientProxy)(nil).SubmitOnboarding), varargs...)
}
