// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: api/recommendation/v1/recommendation.proto

package v1

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// RecommendationServiceService defines service.
type RecommendationServiceService interface {
	Recommend(ctx context.Context, req *RecommendRequest) (*RecommendResponse, error)

	ContentSearch(ctx context.Context, req *ContentSearchRequest) (*ContentSearchResponse, error)

	IngestDocument(ctx context.Context, req *IngestRequest) (*IngestResponse, error)

	SearchTitle(ctx context.Context, req *TitleSearchRequest) (*TitleSearchResponse, error)

	SearchAuthor(ctx context.Context, req *AuthorSearchRequest) (*AuthorSearchResponse, error)

	SubmitOnboarding(ctx context.Context, req *OnboardingRequest) (*OnboardingResponse, error)

	HealthCheck(ctx context.Context, req *HealthRequest) (*HealthResponse, error)

	ListTools(ctx context.Context, req *ToolListRequest) (*ToolListResponse, error)
}

func RecommendationServiceService_Recommend_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RecommendRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).Recommend(ctx, reqbody.(*RecommendRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_ContentSearch_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ContentSearchRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).ContentSearch(ctx, reqbody.(*ContentSearchRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_IngestDocument_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &IngestRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).IngestDocument(ctx, reqbody.(*IngestRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_SearchTitle_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TitleSearchRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).SearchTitle(ctx, reqbody.(*TitleSearchRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_SearchAuthor_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AuthorSearchRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).SearchAuthor(ctx, reqbody.(*AuthorSearchRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_SubmitOnboarding_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &OnboardingRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).SubmitOnboarding(ctx, reqbody.(*OnboardingRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_HealthCheck_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HealthRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).HealthCheck(ctx, reqbody.(*HealthRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func RecommendationServiceService_ListTools_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ToolListRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(RecommendationServiceService).ListTools(ctx, reqbody.(*ToolListRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// RecommendationServiceServer_ServiceDesc descriptor for server.RegisterService.
var RecommendationServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "recommendation.v1.RecommendationService",
	HandlerType: ((*RecommendationServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/recommendation.v1.RecommendationService/Recommend",
			Func: RecommendationServiceService_Recommend_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/ContentSearch",
			Func: RecommendationServiceService_ContentSearch_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/IngestDocument",
			Func: RecommendationServiceService_IngestDocument_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/SearchTitle",
			Func: RecommendationServiceService_SearchTitle_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/SearchAuthor",
			Func: RecommendationServiceService_SearchAuthor_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/SubmitOnboarding",
			Func: RecommendationServiceService_SubmitOnboarding_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/HealthCheck",
			Func: RecommendationServiceService_HealthCheck_Handler,
		},
		{
			Name: "/recommendation.v1.RecommendationService/ListTools",
			Func: RecommendationServiceService_ListTools_Handler,
		},
	},
}

// RegisterRecommendationServiceService registers service.
func RegisterRecommendationServiceService(s server.Service, svr RecommendationServiceService) {
	if err := s.Register(&RecommendationServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("RecommendationService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedRecommendationService struct{}

func (s *UnimplementedRecommendationService) Recommend(ctx context.Context, req *RecommendRequest) (*RecommendResponse, error) {
	return nil, errors.New("rpc Recommend of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) ContentSearch(ctx context.Context, req *ContentSearchRequest) (*ContentSearchResponse, error) {
	return nil, errors.New("rpc ContentSearch of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) IngestDocument(ctx context.Context, req *IngestRequest) (*IngestResponse, error) {
	return nil, errors.New("rpc IngestDocument of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) SearchTitle(ctx context.Context, req *TitleSearchRequest) (*TitleSearchResponse, error) {
	return nil, errors.New("rpc SearchTitle of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) SearchAuthor(ctx context.Context, req *AuthorSearchRequest) (*AuthorSearchResponse, error) {
	return nil, errors.New("rpc SearchAuthor of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) SubmitOnboarding(ctx context.Context, req *OnboardingRequest) (*OnboardingResponse, error) {
	return nil, errors.New("rpc SubmitOnboarding of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) HealthCheck(ctx context.Context, req *HealthRequest) (*HealthResponse, error) {
	return nil, errors.New("rpc HealthCheck of service RecommendationService is not implemented")
}
func (s *UnimplementedRecommendationService) ListTools(ctx context.Context, req *ToolListRequest) (*ToolListResponse, error) {
	return nil, errors.New("rpc ListTools of service RecommendationService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// RecommendationServiceClientProxy defines service client proxy
type RecommendationServiceClientProxy interface {
	Recommend(ctx context.Context, req *RecommendRequest, opts ...client.Option) (rsp *RecommendResponse, err error)

	ContentSearch(ctx context.Context, req *ContentSearchRequest, opts ...client.Option) (rsp *ContentSearchResponse, err error)

	IngestDocument(ctx context.Context, req *IngestRequest, opts ...client.Option) (rsp *IngestResponse, err error)

	SearchTitle(ctx context.Context, req *TitleSearchRequest, opts ...client.Option) (rsp *TitleSearchResponse, err error)

	SearchAuthor(ctx context.Context, req *AuthorSearchRequest, opts ...client.Option) (rsp *AuthorSearchResponse, err error)

	SubmitOnboarding(ctx context.Context, req *OnboardingRequest, opts ...client.Option) (rsp *OnboardingResponse, err error)

	HealthCheck(ctx context.Context, req *HealthRequest, opts ...client.Option) (rsp *HealthResponse, err error)

	ListTools(ctx context.Context, req *ToolListRequest, opts ...client.Option) (rsp *ToolListResponse, err error)
}

type RecommendationServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewRecommendationServiceClientProxy = func(opts ...client.Option) RecommendationServiceClientProxy {
	return &RecommendationServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *RecommendationServiceClientProxyImpl) Recommend(ctx context.Context, req *RecommendRequest, opts ...client.Option) (*RecommendResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/Recommend")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("Recommend")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RecommendResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) ContentSearch(ctx context.Context, req *ContentSearchRequest, opts ...client.Option) (*ContentSearchResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/ContentSearch")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("ContentSearch")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ContentSearchResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) IngestDocument(ctx context.Context, req *IngestRequest, opts ...client.Option) (*IngestResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/IngestDocument")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("IngestDocument")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &IngestResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) SearchTitle(ctx context.Context, req *TitleSearchRequest, opts ...client.Option) (*TitleSearchResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/SearchTitle")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("SearchTitle")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TitleSearchResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) SearchAuthor(ctx context.Context, req *AuthorSearchRequest, opts ...client.Option) (*AuthorSearchResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/SearchAuthor")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("SearchAuthor")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AuthorSearchResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) SubmitOnboarding(ctx context.Context, req *OnboardingRequest, opts ...client.Option) (*OnboardingResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/SubmitOnboarding")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("SubmitOnboarding")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &OnboardingResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) HealthCheck(ctx context.Context, req *HealthRequest, opts ...client.Option) (*HealthResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/HealthCheck")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("HealthCheck")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HealthResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *RecommendationServiceClientProxyImpl) ListTools(ctx context.Context, req *ToolListRequest, opts ...client.Option) (*ToolListResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/recommendation.v1.RecommendationService/ListTools")
	msg.WithCalleeServiceName(RecommendationServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("RecommendationService")
	msg.WithCalleeMethod("ListTools")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ToolListResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
