package search

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Sea-Go/Sea-BreakTheWaves/service/common/corpus"
	btwruntime "github.com/Sea-Go/Sea-BreakTheWaves/service/common/runtime"
	searchdomain "github.com/Sea-Go/Sea-BreakTheWaves/service/search/internal/search"
)

const (
	ToolsRoute         = "/v1/search/tools/search"
	toolsScopeHeader   = "X-Sea-Search-Tools-Scope"
	toolsScopeAudience = "btw.search.tools.v1"
	maxToolsTTLSeconds = 120
	maxToolsClockSkew  = 30
	maxToolsReads      = 8
	maxToolsQuoteRunes = 8192
)

// ToolsRequest is the exact RTW signed child body, including field order.
type ToolsRequest struct {
	ModuleID     string                    `json:"module_id"`
	Query        string                    `json:"query"`
	Depth        searchdomain.Depth        `json:"depth"`
	Intelligence searchdomain.Intelligence `json:"intelligence"`
	SearchID     string                    `json:"search_id"`
	Limits       struct {
		ReadCalls  int `json:"read_calls"`
		QuoteRunes int `json:"quote_runes"`
	} `json:"limits"`
}

// TrustedToolsScope is returned only after the RTW signature and all fixed
// request fields pass. It is never built from public model or client JSON.
type TrustedToolsScope struct {
	Subject                btwruntime.SubjectRef
	SessionID              string
	OperationID            string
	BudgetRef              string
	SearchID               string
	SnapshotRef            string
	Snapshot               searchdomain.Snapshot
	AllowPartial           bool
	AllowLowerIntelligence bool
}

type ToolsScopeResolver interface {
	ResolveTools(context.Context, *http.Request, ToolsRequest) (TrustedToolsScope, error)
}

type ToolsScopeFunc func(context.Context, *http.Request, ToolsRequest) (TrustedToolsScope, error)

func (f ToolsScopeFunc) ResolveTools(ctx context.Context, request *http.Request, body ToolsRequest) (TrustedToolsScope, error) {
	return f(ctx, request, body)
}

// Snapshot stays raw until its RTW-generated bytes have been hashed. BTW's
// equivalent domain struct must not be used to derive the RTW snapshot_ref.
type signedToolsScope struct {
	Audience               string                `json:"aud"`
	Subject                btwruntime.SubjectRef `json:"subject_ref"`
	SessionID              string                `json:"session_id"`
	OperationID            string                `json:"operation_id"`
	BudgetRef              string                `json:"budget_ref"`
	SearchID               string                `json:"search_id"`
	SnapshotRef            string                `json:"snapshot_ref"`
	Snapshot               json.RawMessage       `json:"snapshot"`
	AllowPartial           bool                  `json:"allow_partial"`
	AllowLowerIntelligence bool                  `json:"allow_lower_intelligence"`
	RequestHash            string                `json:"request_hash"`
	IssuedAtUnix           int64                 `json:"issued_at_unix"`
	ExpiresAtUnix          int64                 `json:"expires_at_unix"`
}

// signedToolsScopeV2 changes only the signed audience and SubjectRef shape;
// parent budget and snapshot contracts retain their existing versions.
type signedToolsScopeV2 struct {
	Audience               string          `json:"aud"`
	Subject                signedSubjectV2 `json:"subject_ref"`
	SessionID              string          `json:"session_id"`
	OperationID            string          `json:"operation_id"`
	BudgetRef              string          `json:"budget_ref"`
	SearchID               string          `json:"search_id"`
	SnapshotRef            string          `json:"snapshot_ref"`
	Snapshot               json.RawMessage `json:"snapshot"`
	AllowPartial           bool            `json:"allow_partial"`
	AllowLowerIntelligence bool            `json:"allow_lower_intelligence"`
	RequestHash            string          `json:"request_hash"`
	IssuedAtUnix           int64           `json:"issued_at_unix"`
	ExpiresAtUnix          int64           `json:"expires_at_unix"`
}

// The field order mirrors RTW's generated SearchSnapshot. Round-tripping this
// shape rejects duplicate/missing/unknown nested fields before any Reader.
type rtwSnapshotWire struct {
	ModuleID            string                `json:"module_id"`
	ReleaseID           string                `json:"release_id"`
	Generation          int64                 `json:"generation"`
	PublicationRevision string                `json:"publication_revision"`
	Indexes             map[string]corpus.Ref `json:"indexes"`
	ValidRevisionIDs    []string              `json:"valid_revision_ids"`
}

type SignedToolsScopeResolver struct {
	key []byte
	now func() time.Time
}

func NewSignedToolsScopeResolver(key []byte) (*SignedToolsScopeResolver, error) {
	if len(key) < 32 {
		return nil, ErrInvalidRequest
	}
	return &SignedToolsScopeResolver{key: append([]byte(nil), key...), now: time.Now}, nil
}

func (s *SignedToolsScopeResolver) ResolveTools(_ context.Context, request *http.Request, body ToolsRequest) (TrustedToolsScope, error) {
	if s == nil || len(s.key) < 32 || s.now == nil || request == nil {
		return TrustedToolsScope{}, ErrScopeUnavailable
	}
	values := request.Header.Values(toolsScopeHeader)
	if len(values) != 1 {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	parts := strings.Split(values[0], ".")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	encoding := base64.RawURLEncoding
	payloadBytes, err := encoding.DecodeString(parts[0])
	if err != nil || encoding.EncodeToString(payloadBytes) != parts[0] || len(payloadBytes) > maxBodyBytes*4 {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	signature, err := encoding.DecodeString(parts[1])
	if err != nil || len(signature) != sha256.Size || encoding.EncodeToString(signature) != parts[1] {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	mac := hmac.New(sha256.New, s.key)
	_, _ = mac.Write(payloadBytes)
	if !hmac.Equal(signature, mac.Sum(nil)) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	var payload signedToolsScope
	switch signedScopeAudience(payloadBytes) {
	case toolsScopeAudienceV2:
		var wire signedToolsScopeV2
		if !strictJSON(payloadBytes, &wire) {
			return TrustedToolsScope{}, ErrScopeDenied
		}
		canonical, err := json.Marshal(wire)
		if err != nil || !bytes.Equal(canonical, payloadBytes) {
			return TrustedToolsScope{}, ErrScopeDenied
		}
		subject, ok := wire.Subject.legacySubject()
		if !ok {
			return TrustedToolsScope{}, ErrScopeDenied
		}
		payload = signedToolsScope{Audience: wire.Audience, Subject: subject,
			SessionID: wire.SessionID, OperationID: wire.OperationID, BudgetRef: wire.BudgetRef,
			SearchID: wire.SearchID, SnapshotRef: wire.SnapshotRef, Snapshot: wire.Snapshot,
			AllowPartial: wire.AllowPartial, AllowLowerIntelligence: wire.AllowLowerIntelligence,
			RequestHash: wire.RequestHash, IssuedAtUnix: wire.IssuedAtUnix, ExpiresAtUnix: wire.ExpiresAtUnix}
	default:
		// Keep the published v1 signed JSON and HMAC validation unchanged.
		if !strictJSON(payloadBytes, &payload) {
			return TrustedToolsScope{}, ErrScopeDenied
		}
		canonical, err := json.Marshal(payload)
		if err != nil || !bytes.Equal(canonical, payloadBytes) {
			return TrustedToolsScope{}, ErrScopeDenied
		}
	}
	now := s.now().Unix()
	if (payload.Audience != toolsScopeAudience && payload.Audience != toolsScopeAudienceV2) ||
		payload.IssuedAtUnix > now+maxToolsClockSkew ||
		payload.IssuedAtUnix < now-maxToolsTTLSeconds || payload.ExpiresAtUnix <= now ||
		payload.ExpiresAtUnix <= payload.IssuedAtUnix ||
		payload.ExpiresAtUnix-payload.IssuedAtUnix > maxToolsTTLSeconds ||
		!validToolsSession(payload.SessionID) || !validToolsID(payload.OperationID) ||
		!validToolsID(payload.BudgetRef) || !constantTimeStringEqual(payload.SearchID, body.SearchID) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	if !validLegacySubject(payload.Subject) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	if _, err := payload.Subject.UserKey(); err != nil ||
		strings.TrimSpace(payload.Subject.AuthorityID) == "" || strings.TrimSpace(payload.Subject.TenantID) == "" ||
		strings.TrimSpace(payload.Subject.SubjectID) == "" ||
		len(payload.Subject.AuthorityID) > 200 || len(payload.Subject.TenantID) > 200 || len(payload.Subject.SubjectID) > 200 {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	var wire rtwSnapshotWire
	if !strictJSON(payload.Snapshot, &wire) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	canonicalSnapshot, err := json.Marshal(wire)
	if err != nil || !bytes.Equal(canonicalSnapshot, payload.Snapshot) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	snapshotHash := sha256.Sum256(payload.Snapshot)
	if !constantTimeStringEqual(payload.SnapshotRef, "snapshot_"+hex.EncodeToString(snapshotHash[:])) ||
		!constantTimeStringEqual(wire.ModuleID, body.ModuleID) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	var snapshot searchdomain.Snapshot
	if !strictJSON(payload.Snapshot, &snapshot) {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	if _, err := searchdomain.SearchGraphRunOption(searchdomain.Request{Query: "scope_check",
		Depth: searchdomain.Fast, Intelligence: searchdomain.Low, Snapshot: snapshot}); err != nil {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	requestBytes, err := json.Marshal(body)
	if err != nil {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	wantHash := sha256.Sum256(requestBytes)
	gotHash, err := hex.DecodeString(payload.RequestHash)
	if err != nil || len(gotHash) != sha256.Size || hex.EncodeToString(gotHash) != payload.RequestHash ||
		subtle.ConstantTimeCompare(gotHash, wantHash[:]) != 1 {
		return TrustedToolsScope{}, ErrScopeDenied
	}
	return TrustedToolsScope{Subject: payload.Subject, SessionID: payload.SessionID,
		OperationID: payload.OperationID, BudgetRef: payload.BudgetRef, SearchID: payload.SearchID,
		SnapshotRef: payload.SnapshotRef, Snapshot: copySnapshot(snapshot), AllowPartial: payload.AllowPartial,
		AllowLowerIntelligence: payload.AllowLowerIntelligence}, nil
}

func strictJSON(raw []byte, out any) bool {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	return decoder.Decode(out) == nil && decoder.Decode(new(any)) == io.EOF
}

func validToolsID(value string) bool {
	if value == "" || len(value) > 200 {
		return false
	}
	for _, ch := range value {
		if ch != '-' && ch != '_' && ch != '.' && (ch < '0' || ch > '9') &&
			(ch < 'a' || ch > 'z') && (ch < 'A' || ch > 'Z') {
			return false
		}
	}
	return true
}

func validToolsSession(value string) bool {
	if strings.TrimSpace(value) == "" || len(value) > 200 {
		return false
	}
	for _, ch := range value {
		if ch < 0x20 || ch == 0x7f {
			return false
		}
	}
	return true
}
