// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type EventBatchReq struct {
	Events []map[string]string `json:"events"`
}

type EventBatchResp struct {
	Accepted int32  `json:"accepted"`
	ErrMsg   string `json:"err_msg,optional"`
}

type RecommendItem struct {
	Id        string            `json:"id"`
	ArticleId string            `json:"article_id"`
	Score     float64           `json:"score"`
	Source    string            `json:"source"`
	Rank      int               `json:"rank"`
	Reason    string            `json:"reason,optional"`
	Features  map[string]string `json:"features,optional"`
	ExtInfo   map[string]string `json:"ext_info,optional"`
}

type RecommendReq struct {
	TenantId  string            `json:"tenant_id"`
	RequestId string            `json:"request_id"`
	Scenario  string            `json:"scenario"`
	Channel   string            `json:"channel,optional"`
	UserId    string            `json:"user_id,optional"`
	Query     string            `json:"query,optional"`
	TopK      int32             `json:"top_k,optional"`
	PathMode  string            `json:"path_mode,optional"`
	Debug     bool              `json:"debug,optional"`
	ExtInfo   map[string]string `json:"ext_info,optional"`
}

type RecommendResp struct {
	RequestId string            `json:"request_id"`
	TraceId   string            `json:"trace_id"`
	PathTaken string            `json:"path_taken"`
	Items     []RecommendItem   `json:"items"`
	ErrMsg    string            `json:"err_msg,optional"`
	ExtInfo   map[string]string `json:"ext_info,optional"`
}
