// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: recommend.proto

package server

import (
	"context"

	"github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/rpc/internal/logic"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/rpc/internal/svc"
	recommendpb "github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/rpc/pb"
)

type RecommendServiceServer struct {
	svcCtx *svc.ServiceContext
	recommendpb.UnimplementedRecommendServiceServer
}

func NewRecommendServiceServer(svcCtx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServiceServer) Recommend(ctx context.Context, in *recommendpb.RecommendRequest) (*recommendpb.RecommendResponse, error) {
	l := logic.NewRecommendLogic(ctx, s.svcCtx)
	return l.Recommend(in)
}

func (s *RecommendServiceServer) StreamRecommend(in *recommendpb.RecommendRequest, stream recommendpb.RecommendService_StreamRecommendServer) error {
	l := logic.NewStreamRecommendLogic(stream.Context(), s.svcCtx)
	return l.StreamRecommend(in, stream)
}

func (s *RecommendServiceServer) SubmitEvents(ctx context.Context, in *recommendpb.SubmitEventsRequest) (*recommendpb.SubmitEventsResponse, error) {
	l := logic.NewSubmitEventsLogic(ctx, s.svcCtx)
	return l.SubmitEvents(in)
}

func (s *RecommendServiceServer) ListSkills(ctx context.Context, in *recommendpb.SkillListRequest) (*recommendpb.SkillListResponse, error) {
	l := logic.NewListSkillsLogic(ctx, s.svcCtx)
	return l.ListSkills(in)
}

func (s *RecommendServiceServer) EvaluationSummary(ctx context.Context, in *recommendpb.EvaluationSummaryRequest) (*recommendpb.EvaluationSummaryResponse, error) {
	l := logic.NewEvaluationSummaryLogic(ctx, s.svcCtx)
	return l.EvaluationSummary(in)
}
