// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: async.proto

package asyncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	OccurredAtMs  int64                  `protobuf:"varint,4,opt,name=occurred_at_ms,json=occurredAtMs,proto3" json:"occurred_at_ms,omitempty"`
	VersionMs     int64                  `protobuf:"varint,5,opt,name=version_ms,json=versionMs,proto3" json:"version_ms,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_async_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_async_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_async_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *EventEnvelope) GetOccurredAtMs() int64 {
	if x != nil {
		return x.OccurredAtMs
	}
	return 0
}

func (x *EventEnvelope) GetVersionMs() int64 {
	if x != nil {
		return x.VersionMs
	}
	return 0
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SubmitEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventEnvelope       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEventsRequest) Reset() {
	*x = SubmitEventsRequest{}
	mi := &file_async_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEventsRequest) ProtoMessage() {}

func (x *SubmitEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_async_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEventsRequest.ProtoReflect.Descriptor instead.
func (*SubmitEventsRequest) Descriptor() ([]byte, []int) {
	return file_async_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitEventsRequest) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

type SubmitEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      []string               `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEventsResponse) Reset() {
	*x = SubmitEventsResponse{}
	mi := &file_async_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEventsResponse) ProtoMessage() {}

func (x *SubmitEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_async_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEventsResponse.ProtoReflect.Descriptor instead.
func (*SubmitEventsResponse) Descriptor() ([]byte, []int) {
	return file_async_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitEventsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SubmitEventsResponse) GetRejected() []string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type ProjectionQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Projection    string                 `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectionQuery) Reset() {
	*x = ProjectionQuery{}
	mi := &file_async_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionQuery) ProtoMessage() {}

func (x *ProjectionQuery) ProtoReflect() protoreflect.Message {
	mi := &file_async_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionQuery.ProtoReflect.Descriptor instead.
func (*ProjectionQuery) Descriptor() ([]byte, []int) {
	return file_async_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectionQuery) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ProjectionQuery) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

type ProjectionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Projection    string                 `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	VersionMs     int64                  `protobuf:"varint,3,opt,name=version_ms,json=versionMs,proto3" json:"version_ms,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectionSnapshot) Reset() {
	*x = ProjectionSnapshot{}
	mi := &file_async_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionSnapshot) ProtoMessage() {}

func (x *ProjectionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_async_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionSnapshot.ProtoReflect.Descriptor instead.
func (*ProjectionSnapshot) Descriptor() ([]byte, []int) {
	return file_async_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectionSnapshot) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ProjectionSnapshot) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *ProjectionSnapshot) GetVersionMs() int64 {
	if x != nil {
		return x.VersionMs
	}
	return 0
}

func (x *ProjectionSnapshot) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_async_proto protoreflect.FileDescriptor

const file_async_proto_rawDesc = "" +
	"\n" +
	"\vasync.proto\x12\fsea.async.v1\"\xcb\x01\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12$\n" +
	"\x0eoccurred_at_ms\x18\x04 \x01(\x03R\foccurredAtMs\x12\x1d\n" +
	"\n" +
	"version_ms\x18\x05 \x01(\x03R\tversionMs\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"J\n" +
	"\x13SubmitEventsRequest\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.sea.async.v1.EventEnvelopeR\x06events\"N\n" +
	"\x14SubmitEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x03(\tR\brejected\"P\n" +
	"\x0fProjectionQuery\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x1e\n" +
	"\n" +
	"projection\x18\x02 \x01(\tR\n" +
	"projection\"\x8c\x01\n" +
	"\x12ProjectionSnapshot\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x1e\n" +
	"\n" +
	"projection\x18\x02 \x01(\tR\n" +
	"projection\x12\x1d\n" +
	"\n" +
	"version_ms\x18\x03 \x01(\x03R\tversionMs\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload2\xb7\x01\n" +
	"\fAsyncService\x12U\n" +
	"\fSubmitEvents\x12!.sea.async.v1.SubmitEventsRequest\x1a\".sea.async.v1.SubmitEventsResponse\x12P\n" +
	"\rGetProjection\x12\x1d.sea.async.v1.ProjectionQuery\x1a .sea.async.v1.ProjectionSnapshotBBZ@github.com/Sea-Go/Sea-BreakTheWaves/service/async/rpc/pb;asyncpbb\x06proto3"

var (
	file_async_proto_rawDescOnce sync.Once
	file_async_proto_rawDescData []byte
)

func file_async_proto_rawDescGZIP() []byte {
	file_async_proto_rawDescOnce.Do(func() {
		file_async_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_async_proto_rawDesc), len(file_async_proto_rawDesc)))
	})
	return file_async_proto_rawDescData
}

var file_async_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_async_proto_goTypes = []any{
	(*EventEnvelope)(nil),        // 0: sea.async.v1.EventEnvelope
	(*SubmitEventsRequest)(nil),  // 1: sea.async.v1.SubmitEventsRequest
	(*SubmitEventsResponse)(nil), // 2: sea.async.v1.SubmitEventsResponse
	(*ProjectionQuery)(nil),      // 3: sea.async.v1.ProjectionQuery
	(*ProjectionSnapshot)(nil),   // 4: sea.async.v1.ProjectionSnapshot
}
var file_async_proto_depIdxs = []int32{
	0, // 0: sea.async.v1.SubmitEventsRequest.events:type_name -> sea.async.v1.EventEnvelope
	1, // 1: sea.async.v1.AsyncService.SubmitEvents:input_type -> sea.async.v1.SubmitEventsRequest
	3, // 2: sea.async.v1.AsyncService.GetProjection:input_type -> sea.async.v1.ProjectionQuery
	2, // 3: sea.async.v1.AsyncService.SubmitEvents:output_type -> sea.async.v1.SubmitEventsResponse
	4, // 4: sea.async.v1.AsyncService.GetProjection:output_type -> sea.async.v1.ProjectionSnapshot
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_async_proto_init() }
func file_async_proto_init() {
	if File_async_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_async_proto_rawDesc), len(file_async_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_async_proto_goTypes,
		DependencyIndexes: file_async_proto_depIdxs,
		MessageInfos:      file_async_proto_msgTypes,
	}.Build()
	File_async_proto = out.File
	file_async_proto_goTypes = nil
	file_async_proto_depIdxs = nil
}
