// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: async.proto

package asyncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsyncService_SubmitEvents_FullMethodName  = "/sea.async.v1.AsyncService/SubmitEvents"
	AsyncService_GetProjection_FullMethodName = "/sea.async.v1.AsyncService/GetProjection"
)

// AsyncServiceClient is the client API for AsyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsyncServiceClient interface {
	SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error)
	GetProjection(ctx context.Context, in *ProjectionQuery, opts ...grpc.CallOption) (*ProjectionSnapshot, error)
}

type asyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncServiceClient(cc grpc.ClientConnInterface) AsyncServiceClient {
	return &asyncServiceClient{cc}
}

func (c *asyncServiceClient) SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitEventsResponse)
	err := c.cc.Invoke(ctx, AsyncService_SubmitEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asyncServiceClient) GetProjection(ctx context.Context, in *ProjectionQuery, opts ...grpc.CallOption) (*ProjectionSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectionSnapshot)
	err := c.cc.Invoke(ctx, AsyncService_GetProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsyncServiceServer is the server API for AsyncService service.
// All implementations must embed UnimplementedAsyncServiceServer
// for forward compatibility.
type AsyncServiceServer interface {
	SubmitEvents(context.Context, *SubmitEventsRequest) (*SubmitEventsResponse, error)
	GetProjection(context.Context, *ProjectionQuery) (*ProjectionSnapshot, error)
	mustEmbedUnimplementedAsyncServiceServer()
}

// UnimplementedAsyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsyncServiceServer struct{}

func (UnimplementedAsyncServiceServer) SubmitEvents(context.Context, *SubmitEventsRequest) (*SubmitEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvents not implemented")
}
func (UnimplementedAsyncServiceServer) GetProjection(context.Context, *ProjectionQuery) (*ProjectionSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProjection not implemented")
}
func (UnimplementedAsyncServiceServer) mustEmbedUnimplementedAsyncServiceServer() {}
func (UnimplementedAsyncServiceServer) testEmbeddedByValue()                      {}

// UnsafeAsyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncServiceServer will
// result in compilation errors.
type UnsafeAsyncServiceServer interface {
	mustEmbedUnimplementedAsyncServiceServer()
}

func RegisterAsyncServiceServer(s grpc.ServiceRegistrar, srv AsyncServiceServer) {
	// If the following call panics, it indicates UnimplementedAsyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsyncService_ServiceDesc, srv)
}

func _AsyncService_SubmitEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncServiceServer).SubmitEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncService_SubmitEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncServiceServer).SubmitEvents(ctx, req.(*SubmitEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsyncService_GetProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsyncServiceServer).GetProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsyncService_GetProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsyncServiceServer).GetProjection(ctx, req.(*ProjectionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// AsyncService_ServiceDesc is the grpc.ServiceDesc for AsyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sea.async.v1.AsyncService",
	HandlerType: (*AsyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitEvents",
			Handler:    _AsyncService_SubmitEvents_Handler,
		},
		{
			MethodName: "GetProjection",
			Handler:    _AsyncService_GetProjection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "async.proto",
}
