// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: async.proto

package asyncservice

import (
	"context"

	asyncpb "github.com/Sea-Go/Sea-BreakTheWaves/service/async/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EventEnvelope        = asyncpb.EventEnvelope
	ProjectionQuery      = asyncpb.ProjectionQuery
	ProjectionSnapshot   = asyncpb.ProjectionSnapshot
	SubmitEventsRequest  = asyncpb.SubmitEventsRequest
	SubmitEventsResponse = asyncpb.SubmitEventsResponse

	AsyncService interface {
		SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error)
		GetProjection(ctx context.Context, in *ProjectionQuery, opts ...grpc.CallOption) (*ProjectionSnapshot, error)
	}

	defaultAsyncService struct {
		cli zrpc.Client
	}
)

func NewAsyncService(cli zrpc.Client) AsyncService {
	return &defaultAsyncService{
		cli: cli,
	}
}

func (m *defaultAsyncService) SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error) {
	client := asyncpb.NewAsyncServiceClient(m.cli.Conn())
	return client.SubmitEvents(ctx, in, opts...)
}

func (m *defaultAsyncService) GetProjection(ctx context.Context, in *ProjectionQuery, opts ...grpc.CallOption) (*ProjectionSnapshot, error) {
	client := asyncpb.NewAsyncServiceClient(m.cli.Conn())
	return client.GetProjection(ctx, in, opts...)
}
