// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	recommend "github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/gozero/internal/handler/recommend"
	recommendadmin "github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/gozero/internal/handler/recommendadmin"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/gozero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin/skills",
				Handler: recommend.SkillListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/events",
				Handler: recommend.EventsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recommend",
				Handler: recommend.RecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recommend/stream",
				Handler: recommend.RecommendStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v2"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/reco/evaluation/summary",
				Handler: recommendadmin.EvaluationSummaryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/health",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			httpx.OkJsonCtx(r.Context(), w, map[string]any{"status": "ok", "service": "recommend-api"})
		},
	})
}
