// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: recommend.proto

package recommendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Scenario      string                 `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,7,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	PathMode      string                 `protobuf:"bytes,8,opt,name=path_mode,json=pathMode,proto3" json:"path_mode,omitempty"`
	Debug         bool                   `protobuf:"varint,9,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecommendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecommendRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *RecommendRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RecommendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecommendRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RecommendRequest) GetPathMode() string {
	if x != nil {
		return x.PathMode
	}
	return ""
}

func (x *RecommendRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type RecommendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendItem) Reset() {
	*x = RecommendItem{}
	mi := &file_recommend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendItem) ProtoMessage() {}

func (x *RecommendItem) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendItem.ProtoReflect.Descriptor instead.
func (*RecommendItem) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecommendItem) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *RecommendItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RecommendItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RecommendItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	PathTaken     string                 `protobuf:"bytes,3,opt,name=path_taken,json=pathTaken,proto3" json:"path_taken,omitempty"`
	Items         []*RecommendItem       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_recommend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecommendResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RecommendResponse) GetPathTaken() string {
	if x != nil {
		return x.PathTaken
	}
	return ""
}

func (x *RecommendResponse) GetItems() []*RecommendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BehaviorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,7,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Rank          int32                  `protobuf:"varint,8,opt,name=rank,proto3" json:"rank,omitempty"`
	Channel       string                 `protobuf:"bytes,9,opt,name=channel,proto3" json:"channel,omitempty"`
	PathTaken     string                 `protobuf:"bytes,10,opt,name=path_taken,json=pathTaken,proto3" json:"path_taken,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,11,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BehaviorEvent) Reset() {
	*x = BehaviorEvent{}
	mi := &file_recommend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BehaviorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BehaviorEvent) ProtoMessage() {}

func (x *BehaviorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BehaviorEvent.ProtoReflect.Descriptor instead.
func (*BehaviorEvent) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{3}
}

func (x *BehaviorEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BehaviorEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BehaviorEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BehaviorEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BehaviorEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BehaviorEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BehaviorEvent) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *BehaviorEvent) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *BehaviorEvent) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *BehaviorEvent) GetPathTaken() string {
	if x != nil {
		return x.PathTaken
	}
	return ""
}

func (x *BehaviorEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type SubmitEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*BehaviorEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEventsRequest) Reset() {
	*x = SubmitEventsRequest{}
	mi := &file_recommend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEventsRequest) ProtoMessage() {}

func (x *SubmitEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEventsRequest.ProtoReflect.Descriptor instead.
func (*SubmitEventsRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitEventsRequest) GetEvents() []*BehaviorEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type SubmitEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      []string               `protobuf:"bytes,2,rep,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitEventsResponse) Reset() {
	*x = SubmitEventsResponse{}
	mi := &file_recommend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitEventsResponse) ProtoMessage() {}

func (x *SubmitEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitEventsResponse.ProtoReflect.Descriptor instead.
func (*SubmitEventsResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitEventsResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SubmitEventsResponse) GetRejected() []string {
	if x != nil {
		return x.Rejected
	}
	return nil
}

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CostLevel     string                 `protobuf:"bytes,4,opt,name=cost_level,json=costLevel,proto3" json:"cost_level,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_recommend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{6}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Skill) GetCostLevel() string {
	if x != nil {
		return x.CostLevel
	}
	return ""
}

func (x *Skill) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type SkillListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListRequest) Reset() {
	*x = SkillListRequest{}
	mi := &file_recommend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListRequest) ProtoMessage() {}

func (x *SkillListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListRequest.ProtoReflect.Descriptor instead.
func (*SkillListRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{7}
}

type SkillListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillListResponse) Reset() {
	*x = SkillListResponse{}
	mi := &file_recommend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillListResponse) ProtoMessage() {}

func (x *SkillListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillListResponse.ProtoReflect.Descriptor instead.
func (*SkillListResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{8}
}

func (x *SkillListResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type EvaluationSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Surface       string                 `protobuf:"bytes,1,opt,name=surface,proto3" json:"surface,omitempty"`
	Window        string                 `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationSummaryRequest) Reset() {
	*x = EvaluationSummaryRequest{}
	mi := &file_recommend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationSummaryRequest) ProtoMessage() {}

func (x *EvaluationSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationSummaryRequest.ProtoReflect.Descriptor instead.
func (*EvaluationSummaryRequest) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluationSummaryRequest) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *EvaluationSummaryRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type EvaluationSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationSummaryResponse) Reset() {
	*x = EvaluationSummaryResponse{}
	mi := &file_recommend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationSummaryResponse) ProtoMessage() {}

func (x *EvaluationSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationSummaryResponse.ProtoReflect.Descriptor instead.
func (*EvaluationSummaryResponse) Descriptor() ([]byte, []int) {
	return file_recommend_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluationSummaryResponse) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_recommend_proto protoreflect.FileDescriptor

const file_recommend_proto_rawDesc = "" +
	"\n" +
	"\x0frecommend.proto\x12\x10sea.recommend.v1\"\xfb\x01\n" +
	"\x10RecommendRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bscenario\x18\x03 \x01(\tR\bscenario\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\a \x01(\x05R\x04topK\x12\x1b\n" +
	"\tpath_mode\x18\b \x01(\tR\bpathMode\x12\x14\n" +
	"\x05debug\x18\t \x01(\bR\x05debug\"\x98\x01\n" +
	"\rRecommendItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xc8\x01\n" +
	"\x11RecommendResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"path_taken\x18\x03 \x01(\tR\tpathTaken\x125\n" +
	"\x05items\x18\x04 \x03(\v2\x1f.sea.recommend.v1.RecommendItemR\x05items\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xc8\x02\n" +
	"\rBehaviorEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\a \x01(\tR\tarticleId\x12\x12\n" +
	"\x04rank\x18\b \x01(\x05R\x04rank\x12\x18\n" +
	"\achannel\x18\t \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"path_taken\x18\n" +
	" \x01(\tR\tpathTaken\x12!\n" +
	"\ftimestamp_ms\x18\v \x01(\x03R\vtimestampMs\"N\n" +
	"\x13SubmitEventsRequest\x127\n" +
	"\x06events\x18\x01 \x03(\v2\x1f.sea.recommend.v1.BehaviorEventR\x06events\"N\n" +
	"\x14SubmitEventsResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x03(\tR\brejected\"\x90\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"cost_level\x18\x04 \x01(\tR\tcostLevel\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\"\x12\n" +
	"\x10SkillListRequest\"D\n" +
	"\x11SkillListResponse\x12/\n" +
	"\x06skills\x18\x01 \x03(\v2\x17.sea.recommend.v1.SkillR\x06skills\"L\n" +
	"\x18EvaluationSummaryRequest\x12\x18\n" +
	"\asurface\x18\x01 \x01(\tR\asurface\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06window\"/\n" +
	"\x19EvaluationSummaryResponse\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json2\xea\x03\n" +
	"\x10RecommendService\x12T\n" +
	"\tRecommend\x12\".sea.recommend.v1.RecommendRequest\x1a#.sea.recommend.v1.RecommendResponse\x12\\\n" +
	"\x0fStreamRecommend\x12\".sea.recommend.v1.RecommendRequest\x1a#.sea.recommend.v1.RecommendResponse0\x01\x12]\n" +
	"\fSubmitEvents\x12%.sea.recommend.v1.SubmitEventsRequest\x1a&.sea.recommend.v1.SubmitEventsResponse\x12U\n" +
	"\n" +
	"ListSkills\x12\".sea.recommend.v1.SkillListRequest\x1a#.sea.recommend.v1.SkillListResponse\x12l\n" +
	"\x11EvaluationSummary\x12*.sea.recommend.v1.EvaluationSummaryRequest\x1a+.sea.recommend.v1.EvaluationSummaryResponseBJZHgithub.com/Sea-Go/Sea-BreakTheWaves/service/recommend/rpc/pb;recommendpbb\x06proto3"

var (
	file_recommend_proto_rawDescOnce sync.Once
	file_recommend_proto_rawDescData []byte
)

func file_recommend_proto_rawDescGZIP() []byte {
	file_recommend_proto_rawDescOnce.Do(func() {
		file_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)))
	})
	return file_recommend_proto_rawDescData
}

var file_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recommend_proto_goTypes = []any{
	(*RecommendRequest)(nil),          // 0: sea.recommend.v1.RecommendRequest
	(*RecommendItem)(nil),             // 1: sea.recommend.v1.RecommendItem
	(*RecommendResponse)(nil),         // 2: sea.recommend.v1.RecommendResponse
	(*BehaviorEvent)(nil),             // 3: sea.recommend.v1.BehaviorEvent
	(*SubmitEventsRequest)(nil),       // 4: sea.recommend.v1.SubmitEventsRequest
	(*SubmitEventsResponse)(nil),      // 5: sea.recommend.v1.SubmitEventsResponse
	(*Skill)(nil),                     // 6: sea.recommend.v1.Skill
	(*SkillListRequest)(nil),          // 7: sea.recommend.v1.SkillListRequest
	(*SkillListResponse)(nil),         // 8: sea.recommend.v1.SkillListResponse
	(*EvaluationSummaryRequest)(nil),  // 9: sea.recommend.v1.EvaluationSummaryRequest
	(*EvaluationSummaryResponse)(nil), // 10: sea.recommend.v1.EvaluationSummaryResponse
}
var file_recommend_proto_depIdxs = []int32{
	1,  // 0: sea.recommend.v1.RecommendResponse.items:type_name -> sea.recommend.v1.RecommendItem
	3,  // 1: sea.recommend.v1.SubmitEventsRequest.events:type_name -> sea.recommend.v1.BehaviorEvent
	6,  // 2: sea.recommend.v1.SkillListResponse.skills:type_name -> sea.recommend.v1.Skill
	0,  // 3: sea.recommend.v1.RecommendService.Recommend:input_type -> sea.recommend.v1.RecommendRequest
	0,  // 4: sea.recommend.v1.RecommendService.StreamRecommend:input_type -> sea.recommend.v1.RecommendRequest
	4,  // 5: sea.recommend.v1.RecommendService.SubmitEvents:input_type -> sea.recommend.v1.SubmitEventsRequest
	7,  // 6: sea.recommend.v1.RecommendService.ListSkills:input_type -> sea.recommend.v1.SkillListRequest
	9,  // 7: sea.recommend.v1.RecommendService.EvaluationSummary:input_type -> sea.recommend.v1.EvaluationSummaryRequest
	2,  // 8: sea.recommend.v1.RecommendService.Recommend:output_type -> sea.recommend.v1.RecommendResponse
	2,  // 9: sea.recommend.v1.RecommendService.StreamRecommend:output_type -> sea.recommend.v1.RecommendResponse
	5,  // 10: sea.recommend.v1.RecommendService.SubmitEvents:output_type -> sea.recommend.v1.SubmitEventsResponse
	8,  // 11: sea.recommend.v1.RecommendService.ListSkills:output_type -> sea.recommend.v1.SkillListResponse
	10, // 12: sea.recommend.v1.RecommendService.EvaluationSummary:output_type -> sea.recommend.v1.EvaluationSummaryResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_recommend_proto_init() }
func file_recommend_proto_init() {
	if File_recommend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommend_proto_rawDesc), len(file_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommend_proto_goTypes,
		DependencyIndexes: file_recommend_proto_depIdxs,
		MessageInfos:      file_recommend_proto_msgTypes,
	}.Build()
	File_recommend_proto = out.File
	file_recommend_proto_goTypes = nil
	file_recommend_proto_depIdxs = nil
}
