// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: recommend.proto

package recommendpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendService_Recommend_FullMethodName         = "/sea.recommend.v1.RecommendService/Recommend"
	RecommendService_StreamRecommend_FullMethodName   = "/sea.recommend.v1.RecommendService/StreamRecommend"
	RecommendService_SubmitEvents_FullMethodName      = "/sea.recommend.v1.RecommendService/SubmitEvents"
	RecommendService_ListSkills_FullMethodName        = "/sea.recommend.v1.RecommendService/ListSkills"
	RecommendService_EvaluationSummary_FullMethodName = "/sea.recommend.v1.RecommendService/EvaluationSummary"
)

// RecommendServiceClient is the client API for RecommendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendServiceClient interface {
	Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	StreamRecommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecommendResponse], error)
	SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error)
	ListSkills(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error)
	EvaluationSummary(ctx context.Context, in *EvaluationSummaryRequest, opts ...grpc.CallOption) (*EvaluationSummaryResponse, error)
}

type recommendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendServiceClient(cc grpc.ClientConnInterface) RecommendServiceClient {
	return &recommendServiceClient{cc}
}

func (c *recommendServiceClient) Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, RecommendService_Recommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) StreamRecommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecommendResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecommendService_ServiceDesc.Streams[0], RecommendService_StreamRecommend_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecommendRequest, RecommendResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommendService_StreamRecommendClient = grpc.ServerStreamingClient[RecommendResponse]

func (c *recommendServiceClient) SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitEventsResponse)
	err := c.cc.Invoke(ctx, RecommendService_SubmitEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) ListSkills(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillListResponse)
	err := c.cc.Invoke(ctx, RecommendService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) EvaluationSummary(ctx context.Context, in *EvaluationSummaryRequest, opts ...grpc.CallOption) (*EvaluationSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationSummaryResponse)
	err := c.cc.Invoke(ctx, RecommendService_EvaluationSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServiceServer is the server API for RecommendService service.
// All implementations must embed UnimplementedRecommendServiceServer
// for forward compatibility.
type RecommendServiceServer interface {
	Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error)
	StreamRecommend(*RecommendRequest, grpc.ServerStreamingServer[RecommendResponse]) error
	SubmitEvents(context.Context, *SubmitEventsRequest) (*SubmitEventsResponse, error)
	ListSkills(context.Context, *SkillListRequest) (*SkillListResponse, error)
	EvaluationSummary(context.Context, *EvaluationSummaryRequest) (*EvaluationSummaryResponse, error)
	mustEmbedUnimplementedRecommendServiceServer()
}

// UnimplementedRecommendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendServiceServer struct{}

func (UnimplementedRecommendServiceServer) Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recommend not implemented")
}
func (UnimplementedRecommendServiceServer) StreamRecommend(*RecommendRequest, grpc.ServerStreamingServer[RecommendResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamRecommend not implemented")
}
func (UnimplementedRecommendServiceServer) SubmitEvents(context.Context, *SubmitEventsRequest) (*SubmitEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitEvents not implemented")
}
func (UnimplementedRecommendServiceServer) ListSkills(context.Context, *SkillListRequest) (*SkillListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedRecommendServiceServer) EvaluationSummary(context.Context, *EvaluationSummaryRequest) (*EvaluationSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluationSummary not implemented")
}
func (UnimplementedRecommendServiceServer) mustEmbedUnimplementedRecommendServiceServer() {}
func (UnimplementedRecommendServiceServer) testEmbeddedByValue()                          {}

// UnsafeRecommendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendServiceServer will
// result in compilation errors.
type UnsafeRecommendServiceServer interface {
	mustEmbedUnimplementedRecommendServiceServer()
}

func RegisterRecommendServiceServer(s grpc.ServiceRegistrar, srv RecommendServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendService_ServiceDesc, srv)
}

func _RecommendService_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_Recommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).Recommend(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_StreamRecommend_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecommendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommendServiceServer).StreamRecommend(m, &grpc.GenericServerStream[RecommendRequest, RecommendResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommendService_StreamRecommendServer = grpc.ServerStreamingServer[RecommendResponse]

func _RecommendService_SubmitEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).SubmitEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_SubmitEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).SubmitEvents(ctx, req.(*SubmitEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkillListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ListSkills(ctx, req.(*SkillListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_EvaluationSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).EvaluationSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_EvaluationSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).EvaluationSummary(ctx, req.(*EvaluationSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendService_ServiceDesc is the grpc.ServiceDesc for RecommendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sea.recommend.v1.RecommendService",
	HandlerType: (*RecommendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recommend",
			Handler:    _RecommendService_Recommend_Handler,
		},
		{
			MethodName: "SubmitEvents",
			Handler:    _RecommendService_SubmitEvents_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _RecommendService_ListSkills_Handler,
		},
		{
			MethodName: "EvaluationSummary",
			Handler:    _RecommendService_EvaluationSummary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRecommend",
			Handler:       _RecommendService_StreamRecommend_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recommend.proto",
}
