CREATE TABLE IF NOT EXISTS {database}.ods_community_event (
  producer String,
  source_offset Int64,
  event_id String,
  event_type String,
  aggregate_id String,
  aggregate_version Int64,
  operation_id String,
  occurred_at DateTime64(9, 'UTC'),
  issuer String,
  subject_id String,
  target_type String,
  target_id String,
  target_revision Nullable(String),
  revision_status String,
  operation String,
  source_ref String,
  comment_id Nullable(String),
  parent_comment_id Nullable(String),
  old_state Nullable(Int16),
  new_state Nullable(Int16),
  visibility_state Nullable(Int16),
  search_evidence Nullable(Bool),
  predecessor_event_id Nullable(String),
  event_time DateTime64(9, 'UTC'),
  available_at DateTime64(9, 'UTC'),
  dc_received_at DateTime64(9, 'UTC'),
  source_event_hash String,
  technical_receipt String,
  event_spec String
) ENGINE = MergeTree ORDER BY (producer, source_offset);
