// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: search.proto

package server

import (
	"context"

	"github.com/Sea-Go/Sea-BreakTheWaves/service/search/rpc/internal/logic"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/search/rpc/internal/svc"
	searchpb "github.com/Sea-Go/Sea-BreakTheWaves/service/search/rpc/pb"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	searchpb.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServiceServer) Search(ctx context.Context, in *searchpb.SearchRequest) (*searchpb.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *SearchServiceServer) SearchStructured(ctx context.Context, in *searchpb.StructuredSearchRequest) (*searchpb.SearchResponse, error) {
	l := logic.NewSearchStructuredLogic(ctx, s.svcCtx)
	return l.SearchStructured(in)
}

func (s *SearchServiceServer) Tools(ctx context.Context, in *searchpb.ToolsRequest) (*searchpb.ToolsResponse, error) {
	l := logic.NewToolsLogic(ctx, s.svcCtx)
	return l.Tools(in)
}
