// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: recommend.proto

package recommendservice

import (
	"context"

	recommendpb "github.com/Sea-Go/Sea-BreakTheWaves/service/recommend/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BehaviorEvent                          = recommendpb.BehaviorEvent
	EvaluationSummaryRequest               = recommendpb.EvaluationSummaryRequest
	EvaluationSummaryResponse              = recommendpb.EvaluationSummaryResponse
	RecommendItem                          = recommendpb.RecommendItem
	RecommendRequest                       = recommendpb.RecommendRequest
	RecommendResponse                      = recommendpb.RecommendResponse
	Skill                                  = recommendpb.Skill
	SkillListRequest                       = recommendpb.SkillListRequest
	SkillListResponse                      = recommendpb.SkillListResponse
	SubmitEventsRequest                    = recommendpb.SubmitEventsRequest
	SubmitEventsResponse                   = recommendpb.SubmitEventsResponse
	RecommendService_StreamRecommendClient = recommendpb.RecommendService_StreamRecommendClient

	RecommendService interface {
		Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
		StreamRecommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (recommendpb.RecommendService_StreamRecommendClient, error)
		SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error)
		ListSkills(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error)
		EvaluationSummary(ctx context.Context, in *EvaluationSummaryRequest, opts ...grpc.CallOption) (*EvaluationSummaryResponse, error)
	}

	defaultRecommendService struct {
		cli zrpc.Client
	}
)

func NewRecommendService(cli zrpc.Client) RecommendService {
	return &defaultRecommendService{
		cli: cli,
	}
}

func (m *defaultRecommendService) Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	client := recommendpb.NewRecommendServiceClient(m.cli.Conn())
	return client.Recommend(ctx, in, opts...)
}

func (m *defaultRecommendService) StreamRecommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (recommendpb.RecommendService_StreamRecommendClient, error) {
	client := recommendpb.NewRecommendServiceClient(m.cli.Conn())
	return client.StreamRecommend(ctx, in, opts...)
}

func (m *defaultRecommendService) SubmitEvents(ctx context.Context, in *SubmitEventsRequest, opts ...grpc.CallOption) (*SubmitEventsResponse, error) {
	client := recommendpb.NewRecommendServiceClient(m.cli.Conn())
	return client.SubmitEvents(ctx, in, opts...)
}

func (m *defaultRecommendService) ListSkills(ctx context.Context, in *SkillListRequest, opts ...grpc.CallOption) (*SkillListResponse, error) {
	client := recommendpb.NewRecommendServiceClient(m.cli.Conn())
	return client.ListSkills(ctx, in, opts...)
}

func (m *defaultRecommendService) EvaluationSummary(ctx context.Context, in *EvaluationSummaryRequest, opts ...grpc.CallOption) (*EvaluationSummaryResponse, error) {
	client := recommendpb.NewRecommendServiceClient(m.cli.Conn())
	return client.EvaluationSummary(ctx, in, opts...)
}
