// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: async.proto

package server

import (
	"context"

	"github.com/Sea-Go/Sea-BreakTheWaves/service/async/rpc/internal/logic"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/async/rpc/internal/svc"
	asyncpb "github.com/Sea-Go/Sea-BreakTheWaves/service/async/rpc/pb"
)

type AsyncServiceServer struct {
	svcCtx *svc.ServiceContext
	asyncpb.UnimplementedAsyncServiceServer
}

func NewAsyncServiceServer(svcCtx *svc.ServiceContext) *AsyncServiceServer {
	return &AsyncServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AsyncServiceServer) SubmitEvents(ctx context.Context, in *asyncpb.SubmitEventsRequest) (*asyncpb.SubmitEventsResponse, error) {
	l := logic.NewSubmitEventsLogic(ctx, s.svcCtx)
	return l.SubmitEvents(in)
}

func (s *AsyncServiceServer) GetProjection(ctx context.Context, in *asyncpb.ProjectionQuery) (*asyncpb.ProjectionSnapshot, error) {
	l := logic.NewGetProjectionLogic(ctx, s.svcCtx)
	return l.GetProjection(in)
}
