// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	search "github.com/Sea-Go/Sea-BreakTheWaves/service/search/gozero/internal/handler/search"
	"github.com/Sea-Go/Sea-BreakTheWaves/service/search/gozero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: search.SearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search/authors",
				Handler: search.SearchAuthorsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search/title",
				Handler: search.SearchTitleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/tools",
				Handler: search.ToolsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoute(rest.Route{
		Method: http.MethodGet,
		Path:   "/health",
		Handler: func(w http.ResponseWriter, r *http.Request) {
			httpx.OkJsonCtx(r.Context(), w, map[string]any{"status": "ok", "service": "search-api"})
		},
	})
}
