// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchRequestId string                 `protobuf:"bytes,1,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query           string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	TopK            int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	NeedAnswer      bool                   `protobuf:"varint,6,opt,name=need_answer,json=needAnswer,proto3" json:"need_answer,omitempty"`
	Explain         bool                   `protobuf:"varint,7,opt,name=explain,proto3" json:"explain,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetNeedAnswer() bool {
	if x != nil {
		return x.NeedAnswer
	}
	return false
}

func (x *SearchRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHit) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *SearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SearchRequestId string                 `protobuf:"bytes,2,opt,name=search_request_id,json=searchRequestId,proto3" json:"search_request_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Answer          string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	Hits            []*SearchHit           `protobuf:"bytes,5,rep,name=hits,proto3" json:"hits,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SearchResponse) GetSearchRequestId() string {
	if x != nil {
		return x.SearchRequestId
	}
	return ""
}

func (x *SearchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StructuredSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredSearchRequest) Reset() {
	*x = StructuredSearchRequest{}
	mi := &file_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredSearchRequest) ProtoMessage() {}

func (x *StructuredSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredSearchRequest.ProtoReflect.Descriptor instead.
func (*StructuredSearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{3}
}

func (x *StructuredSearchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StructuredSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *StructuredSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StructuredSearchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsRequest) Reset() {
	*x = ToolsRequest{}
	mi := &file_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsRequest) ProtoMessage() {}

func (x *ToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsRequest.ProtoReflect.Descriptor instead.
func (*ToolsRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{4}
}

type ToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []string               `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolsResponse) Reset() {
	*x = ToolsResponse{}
	mi := &file_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolsResponse) ProtoMessage() {}

func (x *ToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolsResponse.ProtoReflect.Descriptor instead.
func (*ToolsResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{5}
}

func (x *ToolsResponse) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\rsea.search.v1\"\xd9\x01\n" +
	"\rSearchRequest\x12*\n" +
	"\x11search_request_id\x18\x01 \x01(\tR\x0fsearchRequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12\x1f\n" +
	"\vneed_answer\x18\x06 \x01(\bR\n" +
	"needAnswer\x12\x18\n" +
	"\aexplain\x18\a \x01(\bR\aexplain\"p\n" +
	"\tSearchHit\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"\xda\x01\n" +
	"\x0eSearchResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12*\n" +
	"\x11search_request_id\x18\x02 \x01(\tR\x0fsearchRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12,\n" +
	"\x04hits\x18\x05 \x03(\v2\x18.sea.search.v1.SearchHitR\x04hits\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"x\n" +
	"\x17StructuredSearchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x0e\n" +
	"\fToolsRequest\"%\n" +
	"\rToolsResponse\x12\x14\n" +
	"\x05tools\x18\x01 \x03(\tR\x05tools2\xf5\x01\n" +
	"\rSearchService\x12E\n" +
	"\x06Search\x12\x1c.sea.search.v1.SearchRequest\x1a\x1d.sea.search.v1.SearchResponse\x12Y\n" +
	"\x10SearchStructured\x12&.sea.search.v1.StructuredSearchRequest\x1a\x1d.sea.search.v1.SearchResponse\x12B\n" +
	"\x05Tools\x12\x1b.sea.search.v1.ToolsRequest\x1a\x1c.sea.search.v1.ToolsResponseBDZBgithub.com/Sea-Go/Sea-BreakTheWaves/service/search/rpc/pb;searchpbb\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_proto_goTypes = []any{
	(*SearchRequest)(nil),           // 0: sea.search.v1.SearchRequest
	(*SearchHit)(nil),               // 1: sea.search.v1.SearchHit
	(*SearchResponse)(nil),          // 2: sea.search.v1.SearchResponse
	(*StructuredSearchRequest)(nil), // 3: sea.search.v1.StructuredSearchRequest
	(*ToolsRequest)(nil),            // 4: sea.search.v1.ToolsRequest
	(*ToolsResponse)(nil),           // 5: sea.search.v1.ToolsResponse
}
var file_search_proto_depIdxs = []int32{
	1, // 0: sea.search.v1.SearchResponse.hits:type_name -> sea.search.v1.SearchHit
	0, // 1: sea.search.v1.SearchService.Search:input_type -> sea.search.v1.SearchRequest
	3, // 2: sea.search.v1.SearchService.SearchStructured:input_type -> sea.search.v1.StructuredSearchRequest
	4, // 3: sea.search.v1.SearchService.Tools:input_type -> sea.search.v1.ToolsRequest
	2, // 4: sea.search.v1.SearchService.Search:output_type -> sea.search.v1.SearchResponse
	2, // 5: sea.search.v1.SearchService.SearchStructured:output_type -> sea.search.v1.SearchResponse
	5, // 6: sea.search.v1.SearchService.Tools:output_type -> sea.search.v1.ToolsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
