// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: search.proto

package searchservice

import (
	"context"

	searchpb "github.com/Sea-Go/Sea-BreakTheWaves/service/search/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SearchHit               = searchpb.SearchHit
	SearchRequest           = searchpb.SearchRequest
	SearchResponse          = searchpb.SearchResponse
	StructuredSearchRequest = searchpb.StructuredSearchRequest
	ToolsRequest            = searchpb.ToolsRequest
	ToolsResponse           = searchpb.ToolsResponse

	SearchService interface {
		Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
		SearchStructured(ctx context.Context, in *StructuredSearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
		Tools(ctx context.Context, in *ToolsRequest, opts ...grpc.CallOption) (*ToolsResponse, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

func (m *defaultSearchService) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := searchpb.NewSearchServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}

func (m *defaultSearchService) SearchStructured(ctx context.Context, in *StructuredSearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	client := searchpb.NewSearchServiceClient(m.cli.Conn())
	return client.SearchStructured(ctx, in, opts...)
}

func (m *defaultSearchService) Tools(ctx context.Context, in *ToolsRequest, opts ...grpc.CallOption) (*ToolsResponse, error) {
	client := searchpb.NewSearchServiceClient(m.cli.Conn())
	return client.Tools(ctx, in, opts...)
}
